### ISSUE TITLE
Quickstart doesn't work due to AWS Quickstack utilities issue

### ISSUE THREAD

**Issue by phyllipecesar** [aws-quickstart/quickstart-datastax-oss#34]
The quickstart for datastax doesn't work anymore, the s3 files rely on `quickstart-linux-utilites` which unfortunately fail to install due to a version bump on pystache that doesn't support python2 anymore.
Linux utilities are deprecated: https://github.com/aws-quickstart/quickstart-linux-utilities/issues/28
Error is:
```
Collecting pystache>=0.4.0 (from aws-cfn-bootstrap==1.4)
  Downloading https://files.pythonhosted.org/packages/3f/e7/8750ba6c6101d6aa5ceeb20c013adf2c6f3554a12c71d75654b468404bfa/pystache-0.6.0.tar.gz (78kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-wuts1T/pystache/setup.py", line 183
        command = f"pandoc -f markdown-smart --write=rst --output={rst_temp_path} {md_path}"
                                                                                           ^
    SyntaxError: invalid syntax

```

**Comment by avinash122186** [comment]
As a workaround install the pystache=0.5.4 before invoking the AWS Quickstack utilities
